import re
import sys
import os

books = {
          "genesis": "Gen",
          "gn": "Gen",
          "exodus": "Exo",
          "ex": "Exo",
          "leviticus": "Lev",
          "lv": "Lev",
          "numbers": "Num",
          "deuteronomy": "Deut",
          "deut": "Deut",
          "dt": "Deut",
          "joshua": "Josh",
          "josh": "Josh",
          "judges": "Judg",
          "ruth": "Ruth",
          "1 samuel": "1Sam",
          "1 sam": "1Sam",
          "2 samuel": "2Sam",
          "2 sam": "2Sam",
          "1 kings": "1Kings",
          "2 kings": "2Kings",
          "1 chronicles": "1Chron",
          "1 chron": "1Chron",
          "2 chronicles": "2Chron",
          "2 chron": "2Chron",
          "ez": "Ezra",
          "nehemiah": "Neh",
          "neh": "Neh",
          "esth": "Esther",
          "es": "Esther",
          "est": "Esther",
          "job": "Job",
          "jb": "Job",
          "psalm": "Psa",
          "psalms": "Psa",
          "psa": "Psa",
          "ps": "Psa",
          "proverbs": "Prov",
          "prov": "Prov",
          "prv": "Prov",
          "ecclesiastes": "Eccl",
          "eccl": "Eccl",
          "ecc": "Eccl",
          "song of songs": "SOS",
          "song of solomon": "SOS",
          "sos": "SOS",
          "isaiah": "Isa",
          "is": "Isa",
          "jeremiah": "Jer",
          "jer": "Jer",
          "lamentations": "Lam",
          "lam": "Lam",
          "ezekiel": "Ezek",
          "daniel": "Dan",
          "dn": "Dan",
          "hosea": "Hos",
          "obadiah": "Obad",
          "mic": "Micah",
          "nah": "Nahum",
          "habakkuk": "Hab",
          "zephaniah": "Zeph",
          "haggai": "Hag",
          "zechariah": "Zech",
          "malachi": "Mal",
          "matthew": "Matt",
          "mt": "Matt",
          "mk": "Mark",
          "luk": "Luke",
          "jn": "John",
          "ac": "Acts",
          "romans": "Rom",
          "rm": "Rom",
          "1 corinthians": "1Cor",
          "1 cor": "1Cor",
          "2 corinthians": "2Cor",
          "2 cor": "2Cor",
          "galatians": "Gal",
          "ephesians": "Eph",
          "philippians": "Phil",
          "colossians": "Col",
          "1 thessalonians": "1Thes",
          "1 thes": "1Thes",
          "2 thessalonians": "2Thes",
          "2 thes": "2Thes",
          "1 timothy": "1Tim",
          "1 tim": "1Tim",
          "2 timothy": "2Tim",
          "2 tim": "2Tim",
          "tit": "Titus",
          "tt": "Titus",
          "phm": "Philemon",
          "philem": "Philemon",
          "hebrews": "Heb",
          "jam": "James",
          "1 peter": "1Pet",
          "1 pet": "1Pet",
          "2 peter": "2Pet",
          "2 pet": "2Pet",
          "1 john": "1John",
          "1 jn": "1John",
          "2 john": "2John",
          "2 jn": "2John",
          "3 john": "3John",
          "3 jn": "3John",
          "jude": "Jude",
          "jud": "Jude",
          "revelation": "Rev",
          "rv": "Rev",
          "gen": "Gen",
          "exo": "Exo",
          "lev": "Lev",
          "num": "Num",
          "deut": "Deut",
          "josh": "Josh",
          "judg": "Judg",
          "ruth": "Ruth",
          "1sam": "1Sam",
          "2sam": "2Sam",
          "1kings": "1Kings",
          "2kings": "2Kings",
          "1chron": "1Chron",
          "2chron": "2Chron",
          "ezra": "Ezra",
          "neh": "Neh",
          "esther": "Esther",
          "job": "Job",
          "psa": "Psa",
          "prov": "Prov",
          "eccl": "Eccl",
          "sos": "SOS",
          "isa": "Isa",
          "jer": "Jer",
          "lam": "Lam",
          "ezek": "Ezek",
          "dan": "Dan",
          "hos": "Hos",
          "joel": "Joel",
          "amos": "Amos",
          "obad": "Obad",
          "jonah": "Jonah",
          "micah": "Micah",
          "nahum": "Nahum",
          "hab": "Hab",
          "zeph": "Zeph",
          "hag": "Hag",
          "zech": "Zech",
          "mal": "Mal",
          "matt": "Matt",
          "mark": "Mark",
          "luke": "Luke",
          "john": "John",
          "acts": "Acts",
          "rom": "Rom",
          "1cor": "1Cor",
          "2cor": "2Cor",
          "gal": "Gal",
          "eph": "Eph",
          "phil": "Phil",
          "col": "Col",
          "1thes": "1Thes",
          "2thes": "2Thes",
          "1tim": "1Tim",
          "2tim": "2Tim",
          "titus": "Titus",
          "philemon": "Philemon",
          "heb": "Heb",
          "james": "James",
          "1pet": "1Pet",
          "2pet": "2Pet",
          "1john": "1John",
          "2john": "2John",
          "3john": "3John",
          "jude": "Jude",
          "rev": "Rev"
}

def is_book(book):
    return book.lower() in books
